[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs_20']

[phases.install]
cmds = [
  'install-php-extensions intl zip gd exif',
  'composer install --no-dev --optimize-autoloader --no-interaction --ignore-platform-reqs',
  'npm ci',
]

[phases.build]
cmds = [
  'npm run build',
  'php artisan config:clear',
  'php artisan route:clear',
  'php artisan view:clear',
]

[start]
cmd = 'php -S 0.0.0.0:$PORT -t public'
